// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations / db push need a SESSION or DIRECT connection (the transaction
    // pooler can't run them). Prefer DIRECT_URL when set, so DATABASE_URL is free
    // to point at the transaction pooler (port 6543) for the serverless runtime.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
