type DrinkSeed = {
  name: string;
  slug: string;
  brand: string;
  variant?: string;
  categorySlug: string;
  subcategorySlug: string;
  country: string;
  abv: number;
  priceRange: "BUDGET" | "MID_RANGE" | "PREMIUM" | "LUXURY";
  description?: string;
  taste: {
    sweetness: number;
    bitterness: number;
    sourness: number;
    smokiness: number;
    spiciness: number;
    fruitiness: number;
    floral: number;
    body: number;
    finish: number;
  };
  occasions: string[];
  moods: string[];
  foodPairings: string[];
};

export const DRINKS: DrinkSeed[] = [
  // ============ INDIAN WHISKY ============
  {
    name: "Royal Stag",
    slug: "royal-stag",
    brand: "Pernod Ricard",
    categorySlug: "whisky",
    subcategorySlug: "indian-whisky",
    country: "India",
    abv: 42.8,
    priceRange: "BUDGET",
    description: "One of India's most popular whiskies. Smooth, easy drinking.",
    taste: { sweetness: 5, bitterness: 3, sourness: 1, smokiness: 2, spiciness: 2, fruitiness: 3, floral: 1, body: 4, finish: 3 },
    occasions: ["HOUSE_PARTY", "CASUAL_HANGOUT", "WEEKEND_CHILL"],
    moods: ["RELAXED", "ENERGETIC"],
    foodPairings: ["Biryani", "Kebabs", "Paneer Tikka"],
  },
  {
    name: "Blenders Pride",
    slug: "blenders-pride",
    brand: "Pernod Ricard",
    categorySlug: "whisky",
    subcategorySlug: "indian-whisky",
    country: "India",
    abv: 42.8,
    priceRange: "MID_RANGE",
    description: "Premium Indian whisky with a refined taste profile.",
    taste: { sweetness: 4, bitterness: 3, sourness: 1, smokiness: 3, spiciness: 2, fruitiness: 3, floral: 2, body: 5, finish: 4 },
    occasions: ["DATE_NIGHT", "BUSINESS_DINNER", "CELEBRATION"],
    moods: ["SOPHISTICATED", "ROMANTIC"],
    foodPairings: ["Grilled Chicken", "Dark Chocolate", "Aged Cheese"],
  },
  {
    name: "Blenders Pride Reserve Collection",
    slug: "blenders-pride-reserve",
    brand: "Pernod Ricard",
    variant: "Reserve Collection",
    categorySlug: "whisky",
    subcategorySlug: "indian-whisky",
    country: "India",
    abv: 42.8,
    priceRange: "MID_RANGE",
    description: "The premium variant of Blenders Pride with a smoother finish.",
    taste: { sweetness: 5, bitterness: 3, sourness: 1, smokiness: 3, spiciness: 2, fruitiness: 4, floral: 2, body: 6, finish: 5 },
    occasions: ["DATE_NIGHT", "BUSINESS_DINNER"],
    moods: ["SOPHISTICATED"],
    foodPairings: ["Steak", "Mushroom Risotto", "Brie Cheese"],
  },
  {
    name: "Imperial Blue",
    slug: "imperial-blue",
    brand: "Pernod Ricard",
    categorySlug: "whisky",
    subcategorySlug: "indian-whisky",
    country: "India",
    abv: 42.8,
    priceRange: "BUDGET",
    description: "India's largest selling whisky. Accessible and smooth.",
    taste: { sweetness: 5, bitterness: 2, sourness: 1, smokiness: 1, spiciness: 1, fruitiness: 3, floral: 1, body: 3, finish: 2 },
    occasions: ["HOUSE_PARTY", "CASUAL_HANGOUT"],
    moods: ["RELAXED", "ENERGETIC"],
    foodPairings: ["Tandoori Chicken", "French Fries", "Peanuts"],
  },
  {
    name: "McDowell's No. 1",
    slug: "mcdowells-no-1",
    brand: "United Spirits (Diageo)",
    categorySlug: "whisky",
    subcategorySlug: "indian-whisky",
    country: "India",
    abv: 42.8,
    priceRange: "BUDGET",
    description: "Iconic Indian whisky brand, widely available across the country.",
    taste: { sweetness: 4, bitterness: 3, sourness: 1, smokiness: 2, spiciness: 2, fruitiness: 2, floral: 1, body: 4, finish: 3 },
    occasions: ["HOUSE_PARTY", "CASUAL_HANGOUT", "FESTIVAL"],
    moods: ["ENERGETIC", "CELEBRATORY"],
    foodPairings: ["Chicken Tikka", "Seekh Kebab", "Masala Peanuts"],
  },
  {
    name: "Black Dog Triple Gold Reserve",
    slug: "black-dog-triple-gold",
    brand: "United Spirits (Diageo)",
    variant: "Triple Gold Reserve",
    categorySlug: "whisky",
    subcategorySlug: "scotch",
    country: "Scotland",
    abv: 42.8,
    priceRange: "MID_RANGE",
    description: "Triple matured Scotch whisky, smooth with hints of vanilla and fruit.",
    taste: { sweetness: 5, bitterness: 3, sourness: 1, smokiness: 4, spiciness: 2, fruitiness: 5, floral: 2, body: 6, finish: 5 },
    occasions: ["DATE_NIGHT", "CELEBRATION", "BUSINESS_DINNER"],
    moods: ["SOPHISTICATED", "CONTEMPLATIVE"],
    foodPairings: ["Grilled Lamb", "Smoked Salmon", "Dark Chocolate"],
  },
  {
    name: "Black & White",
    slug: "black-and-white",
    brand: "Diageo",
    categorySlug: "whisky",
    subcategorySlug: "scotch",
    country: "Scotland",
    abv: 42.8,
    priceRange: "MID_RANGE",
    description: "Classic blended Scotch with a balanced flavor profile.",
    taste: { sweetness: 4, bitterness: 4, sourness: 1, smokiness: 5, spiciness: 3, fruitiness: 3, floral: 2, body: 5, finish: 4 },
    occasions: ["CASUAL_HANGOUT", "SOLO_RELAXATION"],
    moods: ["CONTEMPLATIVE", "RELAXED"],
    foodPairings: ["Cheese Platter", "Nuts", "Grilled Fish"],
  },
  {
    name: "Johnnie Walker Black Label",
    slug: "johnnie-walker-black",
    brand: "Diageo",
    variant: "Black Label",
    categorySlug: "whisky",
    subcategorySlug: "scotch",
    country: "Scotland",
    abv: 40,
    priceRange: "PREMIUM",
    description: "Iconic 12-year-old blended Scotch. Complex with smoky depth.",
    taste: { sweetness: 4, bitterness: 4, sourness: 1, smokiness: 7, spiciness: 4, fruitiness: 4, floral: 2, body: 7, finish: 7 },
    occasions: ["CELEBRATION", "BUSINESS_DINNER", "DATE_NIGHT"],
    moods: ["SOPHISTICATED", "CONTEMPLATIVE"],
    foodPairings: ["Steak", "Smoked Meat", "Dark Chocolate", "Blue Cheese"],
  },
  {
    name: "Johnnie Walker Red Label",
    slug: "johnnie-walker-red",
    brand: "Diageo",
    variant: "Red Label",
    categorySlug: "whisky",
    subcategorySlug: "scotch",
    country: "Scotland",
    abv: 40,
    priceRange: "MID_RANGE",
    description: "The world's best-selling Scotch whisky. Bold and versatile.",
    taste: { sweetness: 3, bitterness: 4, sourness: 1, smokiness: 5, spiciness: 4, fruitiness: 3, floral: 1, body: 5, finish: 4 },
    occasions: ["HOUSE_PARTY", "CASUAL_HANGOUT"],
    moods: ["ENERGETIC", "ADVENTUROUS"],
    foodPairings: ["BBQ Chicken", "Spicy Wings", "Nachos"],
  },
  {
    name: "Amrut Fusion",
    slug: "amrut-fusion",
    brand: "Amrut Distilleries",
    variant: "Fusion",
    categorySlug: "whisky",
    subcategorySlug: "single-malt",
    country: "India",
    abv: 50,
    priceRange: "PREMIUM",
    description: "Award-winning Indian single malt. Blend of Indian and Scottish barley.",
    taste: { sweetness: 5, bitterness: 4, sourness: 1, smokiness: 6, spiciness: 4, fruitiness: 6, floral: 3, body: 8, finish: 8 },
    occasions: ["CELEBRATION", "SOLO_RELAXATION"],
    moods: ["CONTEMPLATIVE", "SOPHISTICATED"],
    foodPairings: ["Dark Chocolate", "Dried Fruits", "Aged Cheddar"],
  },
  {
    name: "Paul John Brilliance",
    slug: "paul-john-brilliance",
    brand: "John Distilleries",
    variant: "Brilliance",
    categorySlug: "whisky",
    subcategorySlug: "single-malt",
    country: "India",
    abv: 46,
    priceRange: "PREMIUM",
    description: "Goan single malt aged in American bourbon barrels. Tropical fruit notes.",
    taste: { sweetness: 6, bitterness: 3, sourness: 1, smokiness: 3, spiciness: 3, fruitiness: 7, floral: 3, body: 7, finish: 7 },
    occasions: ["DATE_NIGHT", "CELEBRATION", "SOLO_RELAXATION"],
    moods: ["SOPHISTICATED", "ROMANTIC"],
    foodPairings: ["Seafood", "Tropical Fruits", "Vanilla Ice Cream"],
  },
  {
    name: "Antiquity Blue",
    slug: "antiquity-blue",
    brand: "United Spirits (Diageo)",
    categorySlug: "whisky",
    subcategorySlug: "indian-whisky",
    country: "India",
    abv: 42.8,
    priceRange: "MID_RANGE",
    description: "Premium Indian whisky with a smooth, rich character.",
    taste: { sweetness: 4, bitterness: 4, sourness: 1, smokiness: 3, spiciness: 3, fruitiness: 3, floral: 2, body: 5, finish: 4 },
    occasions: ["CASUAL_HANGOUT", "WEEKEND_CHILL"],
    moods: ["RELAXED", "CONTEMPLATIVE"],
    foodPairings: ["Mutton Curry", "Biryani", "Grilled Paneer"],
  },
  {
    name: "Signature",
    slug: "signature-whisky",
    brand: "United Spirits (Diageo)",
    categorySlug: "whisky",
    subcategorySlug: "indian-whisky",
    country: "India",
    abv: 42.8,
    priceRange: "MID_RANGE",
    description: "A smooth blend that has become a staple in Indian bars.",
    taste: { sweetness: 5, bitterness: 3, sourness: 1, smokiness: 2, spiciness: 2, fruitiness: 4, floral: 2, body: 5, finish: 4 },
    occasions: ["CASUAL_HANGOUT", "HOUSE_PARTY"],
    moods: ["RELAXED", "ENERGETIC"],
    foodPairings: ["Butter Chicken", "Fish Fry", "Samosa"],
  },

  // ============ RUM ============
  {
    name: "Old Monk",
    slug: "old-monk",
    brand: "Mohan Meakin",
    categorySlug: "rum",
    subcategorySlug: "dark-rum",
    country: "India",
    abv: 42.8,
    priceRange: "BUDGET",
    description: "Legendary Indian dark rum. A cult classic with decades of loyal followers.",
    taste: { sweetness: 7, bitterness: 2, sourness: 1, smokiness: 3, spiciness: 3, fruitiness: 5, floral: 1, body: 7, finish: 5 },
    occasions: ["HOUSE_PARTY", "CASUAL_HANGOUT", "WEEKEND_CHILL", "SOLO_RELAXATION"],
    moods: ["NOSTALGIC", "RELAXED", "CELEBRATORY"],
    foodPairings: ["Cola", "Chocolate Cake", "Grilled Meat", "Samosa"],
  },
  {
    name: "Bacardi White",
    slug: "bacardi-white",
    brand: "Bacardi",
    categorySlug: "rum",
    subcategorySlug: "white-rum",
    country: "Puerto Rico",
    abv: 37.5,
    priceRange: "MID_RANGE",
    description: "The world's most awarded white rum. Perfect for cocktails.",
    taste: { sweetness: 4, bitterness: 1, sourness: 1, smokiness: 0, spiciness: 1, fruitiness: 4, floral: 2, body: 3, finish: 2 },
    occasions: ["HOUSE_PARTY", "CLUB_NIGHT", "DATE_NIGHT"],
    moods: ["ENERGETIC", "ADVENTUROUS", "CELEBRATORY"],
    foodPairings: ["Lime", "Mint", "Tropical Fruits", "Grilled Shrimp"],
  },
  {
    name: "Captain Morgan Original Spiced",
    slug: "captain-morgan-spiced",
    brand: "Diageo",
    variant: "Original Spiced",
    categorySlug: "rum",
    subcategorySlug: "spiced-rum",
    country: "Jamaica",
    abv: 35,
    priceRange: "MID_RANGE",
    description: "Spiced rum with vanilla and tropical notes. Great mixer.",
    taste: { sweetness: 6, bitterness: 2, sourness: 1, smokiness: 1, spiciness: 5, fruitiness: 4, floral: 1, body: 5, finish: 4 },
    occasions: ["HOUSE_PARTY", "CASUAL_HANGOUT"],
    moods: ["ADVENTUROUS", "ENERGETIC"],
    foodPairings: ["Apple Pie", "Vanilla Ice Cream", "BBQ Ribs"],
  },
  {
    name: "Havana Club 3 Year",
    slug: "havana-club-3",
    brand: "Pernod Ricard",
    variant: "3 Year",
    categorySlug: "rum",
    subcategorySlug: "white-rum",
    country: "Cuba",
    abv: 40,
    priceRange: "MID_RANGE",
    description: "Authentic Cuban rum. Ideal for Mojitos and Daiquiris.",
    taste: { sweetness: 4, bitterness: 2, sourness: 1, smokiness: 1, spiciness: 2, fruitiness: 5, floral: 2, body: 4, finish: 3 },
    occasions: ["DATE_NIGHT", "HOUSE_PARTY"],
    moods: ["ROMANTIC", "ADVENTUROUS"],
    foodPairings: ["Ceviche", "Grilled Fish", "Mojito ingredients"],
  },
  {
    name: "Maka Zai",
    slug: "maka-zai",
    brand: "Small Batch Spirits",
    categorySlug: "rum",
    subcategorySlug: "indian-rum",
    country: "India",
    abv: 42.8,
    priceRange: "PREMIUM",
    description: "Goan craft rum made from local sugarcane. Rich and complex.",
    taste: { sweetness: 6, bitterness: 3, sourness: 1, smokiness: 2, spiciness: 3, fruitiness: 6, floral: 2, body: 7, finish: 6 },
    occasions: ["DATE_NIGHT", "SOLO_RELAXATION"],
    moods: ["SOPHISTICATED", "CONTEMPLATIVE"],
    foodPairings: ["Goan Fish Curry", "Prawn Balchao", "Dark Chocolate"],
  },

  // ============ VODKA ============
  {
    name: "Absolut",
    slug: "absolut-vodka",
    brand: "Pernod Ricard",
    categorySlug: "vodka",
    subcategorySlug: "plain-vodka",
    country: "Sweden",
    abv: 40,
    priceRange: "MID_RANGE",
    description: "Swedish vodka made from winter wheat. Clean and versatile.",
    taste: { sweetness: 2, bitterness: 1, sourness: 1, smokiness: 0, spiciness: 1, fruitiness: 2, floral: 1, body: 3, finish: 2 },
    occasions: ["CLUB_NIGHT", "HOUSE_PARTY"],
    moods: ["ENERGETIC", "CELEBRATORY"],
    foodPairings: ["Caviar", "Smoked Salmon", "Pickles"],
  },
  {
    name: "Smirnoff No. 21",
    slug: "smirnoff-21",
    brand: "Diageo",
    variant: "No. 21",
    categorySlug: "vodka",
    subcategorySlug: "plain-vodka",
    country: "India",
    abv: 37.5,
    priceRange: "BUDGET",
    description: "Triple distilled vodka. Classic, clean taste.",
    taste: { sweetness: 2, bitterness: 1, sourness: 0, smokiness: 0, spiciness: 1, fruitiness: 1, floral: 0, body: 2, finish: 2 },
    occasions: ["HOUSE_PARTY", "CLUB_NIGHT"],
    moods: ["ENERGETIC", "CELEBRATORY"],
    foodPairings: ["Orange Juice", "Cranberry Juice", "Tonic Water"],
  },
  {
    name: "Grey Goose",
    slug: "grey-goose",
    brand: "Bacardi",
    categorySlug: "vodka",
    subcategorySlug: "premium-vodka",
    country: "France",
    abv: 40,
    priceRange: "PREMIUM",
    description: "French wheat vodka. Exceptionally smooth and clean.",
    taste: { sweetness: 3, bitterness: 1, sourness: 0, smokiness: 0, spiciness: 1, fruitiness: 2, floral: 2, body: 4, finish: 3 },
    occasions: ["DATE_NIGHT", "CELEBRATION", "CLUB_NIGHT"],
    moods: ["SOPHISTICATED", "CELEBRATORY"],
    foodPairings: ["Oysters", "Sushi", "Caviar"],
  },
  {
    name: "Magic Moments",
    slug: "magic-moments",
    brand: "Radico Khaitan",
    categorySlug: "vodka",
    subcategorySlug: "plain-vodka",
    country: "India",
    abv: 37.5,
    priceRange: "BUDGET",
    description: "India's largest selling vodka. Smooth and affordable.",
    taste: { sweetness: 3, bitterness: 1, sourness: 0, smokiness: 0, spiciness: 1, fruitiness: 2, floral: 1, body: 2, finish: 2 },
    occasions: ["HOUSE_PARTY", "CLUB_NIGHT", "CASUAL_HANGOUT"],
    moods: ["ENERGETIC", "CELEBRATORY"],
    foodPairings: ["Fruit Juice", "Tonic Water", "Chips"],
  },

  // ============ GIN ============
  {
    name: "Greater Than",
    slug: "greater-than-gin",
    brand: "Nao Spirits",
    categorySlug: "gin",
    subcategorySlug: "indian-craft-gin",
    country: "India",
    abv: 42.8,
    priceRange: "MID_RANGE",
    description: "India's first craft gin. Citrus-forward with Indian botanicals.",
    taste: { sweetness: 2, bitterness: 4, sourness: 3, smokiness: 0, spiciness: 3, fruitiness: 6, floral: 5, body: 4, finish: 4 },
    occasions: ["DATE_NIGHT", "CASUAL_HANGOUT", "WEEKEND_CHILL"],
    moods: ["SOPHISTICATED", "ADVENTUROUS"],
    foodPairings: ["Tonic Water", "Fish Tacos", "Cucumber Sandwiches"],
  },
  {
    name: "Hapusa",
    slug: "hapusa-gin",
    brand: "Nao Spirits",
    categorySlug: "gin",
    subcategorySlug: "indian-craft-gin",
    country: "India",
    abv: 43,
    priceRange: "PREMIUM",
    description: "Himalayan juniper gin. Earthy, herbal, distinctly Indian.",
    taste: { sweetness: 2, bitterness: 5, sourness: 2, smokiness: 1, spiciness: 4, fruitiness: 4, floral: 6, body: 5, finish: 5 },
    occasions: ["DATE_NIGHT", "SOLO_RELAXATION"],
    moods: ["CONTEMPLATIVE", "SOPHISTICATED"],
    foodPairings: ["Tonic Water", "Indian Spiced Food", "Goat Cheese"],
  },
  {
    name: "Bombay Sapphire",
    slug: "bombay-sapphire",
    brand: "Bacardi",
    categorySlug: "gin",
    subcategorySlug: "london-dry-gin",
    country: "England",
    abv: 47,
    priceRange: "PREMIUM",
    description: "Iconic London Dry Gin with 10 exotic botanicals.",
    taste: { sweetness: 2, bitterness: 5, sourness: 2, smokiness: 0, spiciness: 4, fruitiness: 5, floral: 6, body: 5, finish: 5 },
    occasions: ["DATE_NIGHT", "BUSINESS_DINNER"],
    moods: ["SOPHISTICATED", "ROMANTIC"],
    foodPairings: ["Tonic Water", "Cucumber", "Smoked Salmon"],
  },
  {
    name: "Tanqueray",
    slug: "tanqueray",
    brand: "Diageo",
    categorySlug: "gin",
    subcategorySlug: "london-dry-gin",
    country: "England",
    abv: 43.1,
    priceRange: "PREMIUM",
    description: "Classic London Dry Gin. Four-times distilled with four botanicals.",
    taste: { sweetness: 1, bitterness: 6, sourness: 2, smokiness: 0, spiciness: 4, fruitiness: 3, floral: 4, body: 5, finish: 5 },
    occasions: ["DATE_NIGHT", "BUSINESS_DINNER", "CASUAL_HANGOUT"],
    moods: ["SOPHISTICATED"],
    foodPairings: ["G&T", "Olives", "Grilled Prawns"],
  },
  {
    name: "Stranger & Sons",
    slug: "stranger-and-sons",
    brand: "Third Eye Distillery",
    categorySlug: "gin",
    subcategorySlug: "indian-craft-gin",
    country: "India",
    abv: 42.8,
    priceRange: "PREMIUM",
    description: "Goa-made gin with citrus peel, mango, black pepper and nutmeg.",
    taste: { sweetness: 3, bitterness: 4, sourness: 3, smokiness: 0, spiciness: 5, fruitiness: 7, floral: 5, body: 5, finish: 5 },
    occasions: ["DATE_NIGHT", "CELEBRATION"],
    moods: ["ADVENTUROUS", "SOPHISTICATED"],
    foodPairings: ["Goan Prawn Curry", "Mango Salsa", "Spiced Nuts"],
  },

  // ============ BEER ============
  {
    name: "Kingfisher Premium",
    slug: "kingfisher-premium",
    brand: "United Breweries",
    categorySlug: "beer",
    subcategorySlug: "lager",
    country: "India",
    abv: 4.8,
    priceRange: "BUDGET",
    description: "India's most popular beer. Light, crisp, refreshing.",
    taste: { sweetness: 2, bitterness: 3, sourness: 1, smokiness: 0, spiciness: 0, fruitiness: 1, floral: 0, body: 3, finish: 2 },
    occasions: ["CASUAL_HANGOUT", "HOUSE_PARTY", "OUTDOOR_BBQ", "FESTIVAL"],
    moods: ["RELAXED", "ENERGETIC", "CELEBRATORY"],
    foodPairings: ["Biryani", "Pizza", "Tandoori Chicken", "Peanuts"],
  },
  {
    name: "Kingfisher Strong",
    slug: "kingfisher-strong",
    brand: "United Breweries",
    variant: "Strong",
    categorySlug: "beer",
    subcategorySlug: "strong-beer",
    country: "India",
    abv: 8,
    priceRange: "BUDGET",
    description: "Strong variant of Kingfisher. Bold and higher ABV.",
    taste: { sweetness: 2, bitterness: 4, sourness: 1, smokiness: 0, spiciness: 0, fruitiness: 1, floral: 0, body: 5, finish: 3 },
    occasions: ["HOUSE_PARTY", "CASUAL_HANGOUT"],
    moods: ["ENERGETIC"],
    foodPairings: ["Spicy Wings", "Chilli Chicken", "Kebabs"],
  },
  {
    name: "Bira 91 White",
    slug: "bira-91-white",
    brand: "B9 Beverages",
    variant: "White",
    categorySlug: "beer",
    subcategorySlug: "wheat-beer",
    country: "India",
    abv: 4.7,
    priceRange: "MID_RANGE",
    description: "Indian craft wheat beer with citrusy, light flavors.",
    taste: { sweetness: 4, bitterness: 2, sourness: 2, smokiness: 0, spiciness: 1, fruitiness: 5, floral: 2, body: 3, finish: 2 },
    occasions: ["DATE_NIGHT", "CASUAL_HANGOUT", "OUTDOOR_BBQ"],
    moods: ["RELAXED", "ROMANTIC"],
    foodPairings: ["Salads", "Sushi", "Light Pasta", "Fish & Chips"],
  },
  {
    name: "Bira 91 Blonde",
    slug: "bira-91-blonde",
    brand: "B9 Beverages",
    variant: "Blonde",
    categorySlug: "beer",
    subcategorySlug: "lager",
    country: "India",
    abv: 4.5,
    priceRange: "MID_RANGE",
    description: "Light, sessionable lager with a hint of sweetness.",
    taste: { sweetness: 3, bitterness: 3, sourness: 1, smokiness: 0, spiciness: 0, fruitiness: 3, floral: 1, body: 3, finish: 2 },
    occasions: ["CASUAL_HANGOUT", "OUTDOOR_BBQ", "WEEKEND_CHILL"],
    moods: ["RELAXED"],
    foodPairings: ["Burgers", "Fries", "Grilled Vegetables"],
  },
  {
    name: "Tuborg Strong",
    slug: "tuborg-strong",
    brand: "Carlsberg",
    variant: "Strong",
    categorySlug: "beer",
    subcategorySlug: "strong-beer",
    country: "India",
    abv: 8,
    priceRange: "BUDGET",
    description: "Strong premium beer. Popular in Indian metros.",
    taste: { sweetness: 2, bitterness: 4, sourness: 1, smokiness: 0, spiciness: 0, fruitiness: 1, floral: 0, body: 5, finish: 3 },
    occasions: ["HOUSE_PARTY", "CASUAL_HANGOUT"],
    moods: ["ENERGETIC"],
    foodPairings: ["Chicken Lollipop", "Momos", "Pav Bhaji"],
  },
  {
    name: "Carlsberg Elephant",
    slug: "carlsberg-elephant",
    brand: "Carlsberg",
    variant: "Elephant",
    categorySlug: "beer",
    subcategorySlug: "strong-beer",
    country: "Denmark",
    abv: 7.2,
    priceRange: "MID_RANGE",
    description: "Strong lager with a smooth, full-bodied flavor.",
    taste: { sweetness: 3, bitterness: 4, sourness: 1, smokiness: 0, spiciness: 0, fruitiness: 2, floral: 0, body: 6, finish: 4 },
    occasions: ["CASUAL_HANGOUT", "HOUSE_PARTY"],
    moods: ["RELAXED"],
    foodPairings: ["Grilled Sausages", "Pizza", "Nachos"],
  },
  {
    name: "Heineken",
    slug: "heineken",
    brand: "Heineken",
    categorySlug: "beer",
    subcategorySlug: "lager",
    country: "Netherlands",
    abv: 5,
    priceRange: "MID_RANGE",
    description: "Globally iconic lager with a mild bitter taste.",
    taste: { sweetness: 2, bitterness: 4, sourness: 1, smokiness: 0, spiciness: 0, fruitiness: 2, floral: 1, body: 3, finish: 3 },
    occasions: ["CASUAL_HANGOUT", "DATE_NIGHT", "BUSINESS_DINNER"],
    moods: ["SOPHISTICATED", "RELAXED"],
    foodPairings: ["Burger", "Fries", "Sushi"],
  },
  {
    name: "Simba Wit",
    slug: "simba-wit",
    brand: "Simba Beer",
    variant: "Wit",
    categorySlug: "beer",
    subcategorySlug: "wheat-beer",
    country: "India",
    abv: 5,
    priceRange: "MID_RANGE",
    description: "Indian craft witbier with orange peel and coriander.",
    taste: { sweetness: 4, bitterness: 2, sourness: 2, smokiness: 0, spiciness: 2, fruitiness: 5, floral: 3, body: 3, finish: 2 },
    occasions: ["CASUAL_HANGOUT", "DATE_NIGHT"],
    moods: ["RELAXED", "ADVENTUROUS"],
    foodPairings: ["Seafood", "Light Salads", "Momos"],
  },

  // ============ WINE ============
  {
    name: "Sula Sauvignon Blanc",
    slug: "sula-sauvignon-blanc",
    brand: "Sula Vineyards",
    categorySlug: "wine",
    subcategorySlug: "white-wine",
    country: "India",
    abv: 12.5,
    priceRange: "MID_RANGE",
    description: "India's most popular white wine. Crisp and citrusy from Nashik.",
    taste: { sweetness: 3, bitterness: 2, sourness: 5, smokiness: 0, spiciness: 1, fruitiness: 7, floral: 3, body: 3, finish: 3 },
    occasions: ["DATE_NIGHT", "CASUAL_HANGOUT", "BUSINESS_DINNER"],
    moods: ["ROMANTIC", "SOPHISTICATED", "RELAXED"],
    foodPairings: ["Grilled Fish", "Goat Cheese", "Caesar Salad", "Thai Food"],
  },
  {
    name: "Sula Shiraz",
    slug: "sula-shiraz",
    brand: "Sula Vineyards",
    categorySlug: "wine",
    subcategorySlug: "red-wine",
    country: "India",
    abv: 13,
    priceRange: "MID_RANGE",
    description: "Full-bodied Indian red with berry and spice notes.",
    taste: { sweetness: 3, bitterness: 5, sourness: 3, smokiness: 2, spiciness: 4, fruitiness: 6, floral: 2, body: 7, finish: 5 },
    occasions: ["DATE_NIGHT", "CELEBRATION", "BUSINESS_DINNER"],
    moods: ["ROMANTIC", "SOPHISTICATED"],
    foodPairings: ["Steak", "Lamb Chops", "Aged Cheese", "Dark Chocolate"],
  },
  {
    name: "Fratelli Sette",
    slug: "fratelli-sette",
    brand: "Fratelli Wines",
    categorySlug: "wine",
    subcategorySlug: "red-wine",
    country: "India",
    abv: 13.5,
    priceRange: "MID_RANGE",
    description: "Premium Indian red blend. Rich and well-structured.",
    taste: { sweetness: 3, bitterness: 5, sourness: 3, smokiness: 2, spiciness: 3, fruitiness: 6, floral: 2, body: 7, finish: 6 },
    occasions: ["DATE_NIGHT", "CELEBRATION"],
    moods: ["SOPHISTICATED", "ROMANTIC"],
    foodPairings: ["Pasta", "Grilled Lamb", "Mushroom Risotto"],
  },
  {
    name: "York Arros",
    slug: "york-arros",
    brand: "York Winery",
    categorySlug: "wine",
    subcategorySlug: "rose-wine",
    country: "India",
    abv: 12,
    priceRange: "MID_RANGE",
    description: "Refreshing Indian rose. Strawberry and floral notes.",
    taste: { sweetness: 5, bitterness: 2, sourness: 3, smokiness: 0, spiciness: 1, fruitiness: 7, floral: 5, body: 3, finish: 3 },
    occasions: ["DATE_NIGHT", "CASUAL_HANGOUT", "OUTDOOR_BBQ"],
    moods: ["ROMANTIC", "RELAXED"],
    foodPairings: ["Bruschetta", "Grilled Shrimp", "Fruit Salad"],
  },

  // ============ BRANDY ============
  {
    name: "Morpheus XO",
    slug: "morpheus-xo",
    brand: "Radico Khaitan",
    variant: "XO",
    categorySlug: "brandy",
    subcategorySlug: "indian-brandy",
    country: "India",
    abv: 42.8,
    priceRange: "MID_RANGE",
    description: "Premium Indian brandy with rich, smooth character.",
    taste: { sweetness: 6, bitterness: 3, sourness: 1, smokiness: 2, spiciness: 2, fruitiness: 5, floral: 2, body: 6, finish: 5 },
    occasions: ["SOLO_RELAXATION", "BUSINESS_DINNER"],
    moods: ["CONTEMPLATIVE", "SOPHISTICATED"],
    foodPairings: ["Dark Chocolate", "Dried Fruits", "Cheese"],
  },
  {
    name: "Honey Bee",
    slug: "honey-bee-brandy",
    brand: "United Spirits (Diageo)",
    categorySlug: "brandy",
    subcategorySlug: "indian-brandy",
    country: "India",
    abv: 42.8,
    priceRange: "BUDGET",
    description: "India's leading brandy brand. Smooth and accessible.",
    taste: { sweetness: 6, bitterness: 2, sourness: 1, smokiness: 1, spiciness: 1, fruitiness: 4, floral: 1, body: 4, finish: 3 },
    occasions: ["CASUAL_HANGOUT", "HOUSE_PARTY"],
    moods: ["RELAXED"],
    foodPairings: ["Fried Chicken", "Peanuts", "Banana Chips"],
  },

  // ============ TEQUILA ============
  {
    name: "Jose Cuervo Especial Silver",
    slug: "jose-cuervo-silver",
    brand: "Jose Cuervo",
    variant: "Especial Silver",
    categorySlug: "tequila",
    subcategorySlug: "tequila-blanco",
    country: "Mexico",
    abv: 38,
    priceRange: "MID_RANGE",
    description: "The world's best-selling tequila. Clean agave flavor.",
    taste: { sweetness: 3, bitterness: 2, sourness: 2, smokiness: 0, spiciness: 3, fruitiness: 3, floral: 1, body: 3, finish: 3 },
    occasions: ["HOUSE_PARTY", "CLUB_NIGHT", "CELEBRATION"],
    moods: ["ENERGETIC", "CELEBRATORY", "ADVENTUROUS"],
    foodPairings: ["Lime", "Salt", "Tacos", "Nachos"],
  },
  {
    name: "Patron Silver",
    slug: "patron-silver",
    brand: "Patron",
    variant: "Silver",
    categorySlug: "tequila",
    subcategorySlug: "tequila-blanco",
    country: "Mexico",
    abv: 40,
    priceRange: "PREMIUM",
    description: "Ultra-premium blanco tequila. Smooth and citrusy.",
    taste: { sweetness: 3, bitterness: 2, sourness: 3, smokiness: 0, spiciness: 3, fruitiness: 5, floral: 2, body: 4, finish: 4 },
    occasions: ["CELEBRATION", "DATE_NIGHT", "CLUB_NIGHT"],
    moods: ["SOPHISTICATED", "CELEBRATORY"],
    foodPairings: ["Ceviche", "Grilled Shrimp", "Guacamole"],
  },

  // ============ LIQUEUR ============
  {
    name: "Baileys Irish Cream",
    slug: "baileys",
    brand: "Diageo",
    categorySlug: "liqueur",
    subcategorySlug: "cream-liqueur",
    country: "Ireland",
    abv: 17,
    priceRange: "MID_RANGE",
    description: "The original Irish cream liqueur. Rich, chocolatey, smooth.",
    taste: { sweetness: 8, bitterness: 1, sourness: 0, smokiness: 0, spiciness: 0, fruitiness: 2, floral: 1, body: 7, finish: 4 },
    occasions: ["DATE_NIGHT", "SOLO_RELAXATION", "CELEBRATION"],
    moods: ["ROMANTIC", "RELAXED"],
    foodPairings: ["Coffee", "Ice Cream", "Chocolate Cake", "Brownies"],
  },
  {
    name: "Kahlua",
    slug: "kahlua",
    brand: "Pernod Ricard",
    categorySlug: "liqueur",
    subcategorySlug: "coffee-liqueur",
    country: "Mexico",
    abv: 20,
    priceRange: "MID_RANGE",
    description: "Coffee liqueur with rum base. Essential for cocktails.",
    taste: { sweetness: 8, bitterness: 4, sourness: 0, smokiness: 0, spiciness: 1, fruitiness: 1, floral: 0, body: 6, finish: 4 },
    occasions: ["DATE_NIGHT", "SOLO_RELAXATION", "HOUSE_PARTY"],
    moods: ["RELAXED", "ROMANTIC"],
    foodPairings: ["Tiramisu", "Espresso", "Vanilla Ice Cream"],
  },
  {
    name: "Jagermeister",
    slug: "jagermeister",
    brand: "Mast-Jagermeister",
    categorySlug: "liqueur",
    subcategorySlug: "herbal-liqueur",
    country: "Germany",
    abv: 35,
    priceRange: "MID_RANGE",
    description: "Iconic herbal liqueur with 56 botanicals. Best served ice cold.",
    taste: { sweetness: 5, bitterness: 5, sourness: 1, smokiness: 0, spiciness: 4, fruitiness: 3, floral: 3, body: 6, finish: 5 },
    occasions: ["CLUB_NIGHT", "HOUSE_PARTY", "FESTIVAL"],
    moods: ["ENERGETIC", "ADVENTUROUS"],
    foodPairings: ["Red Bull", "Dark Chocolate", "Gummy Bears"],
  },
];
