export const CATEGORIES = [
  {
    name: "Whisky",
    slug: "whisky",
    description: "Distilled spirit made from fermented grain mash",
    sortOrder: 1,
    subcategories: [
      { name: "Scotch", slug: "scotch", sortOrder: 1 },
      { name: "Indian Whisky", slug: "indian-whisky", sortOrder: 2 },
      { name: "Bourbon", slug: "bourbon", sortOrder: 3 },
      { name: "Irish Whiskey", slug: "irish-whiskey", sortOrder: 4 },
      { name: "Japanese Whisky", slug: "japanese-whisky", sortOrder: 5 },
      { name: "Blended", slug: "blended-whisky", sortOrder: 6 },
      { name: "Single Malt", slug: "single-malt", sortOrder: 7 },
    ],
  },
  {
    name: "Rum",
    slug: "rum",
    description: "Distilled spirit made from sugarcane",
    sortOrder: 2,
    subcategories: [
      { name: "Dark Rum", slug: "dark-rum", sortOrder: 1 },
      { name: "White Rum", slug: "white-rum", sortOrder: 2 },
      { name: "Spiced Rum", slug: "spiced-rum", sortOrder: 3 },
      { name: "Gold Rum", slug: "gold-rum", sortOrder: 4 },
      { name: "Indian Rum", slug: "indian-rum", sortOrder: 5 },
    ],
  },
  {
    name: "Vodka",
    slug: "vodka",
    description: "Clear distilled spirit",
    sortOrder: 3,
    subcategories: [
      { name: "Plain Vodka", slug: "plain-vodka", sortOrder: 1 },
      { name: "Flavored Vodka", slug: "flavored-vodka", sortOrder: 2 },
      { name: "Premium Vodka", slug: "premium-vodka", sortOrder: 3 },
    ],
  },
  {
    name: "Gin",
    slug: "gin",
    description: "Juniper-flavored spirit",
    sortOrder: 4,
    subcategories: [
      { name: "London Dry", slug: "london-dry-gin", sortOrder: 1 },
      { name: "Indian Craft Gin", slug: "indian-craft-gin", sortOrder: 2 },
      { name: "Flavored Gin", slug: "flavored-gin", sortOrder: 3 },
    ],
  },
  {
    name: "Beer",
    slug: "beer",
    description: "Fermented grain beverage",
    sortOrder: 5,
    subcategories: [
      { name: "Lager", slug: "lager", sortOrder: 1 },
      { name: "Ale", slug: "ale", sortOrder: 2 },
      { name: "Wheat Beer", slug: "wheat-beer", sortOrder: 3 },
      { name: "Stout", slug: "stout", sortOrder: 4 },
      { name: "IPA", slug: "ipa", sortOrder: 5 },
      { name: "Craft Beer", slug: "craft-beer", sortOrder: 6 },
      { name: "Strong Beer", slug: "strong-beer", sortOrder: 7 },
    ],
  },
  {
    name: "Wine",
    slug: "wine",
    description: "Fermented grape beverage",
    sortOrder: 6,
    subcategories: [
      { name: "Red Wine", slug: "red-wine", sortOrder: 1 },
      { name: "White Wine", slug: "white-wine", sortOrder: 2 },
      { name: "Rose", slug: "rose-wine", sortOrder: 3 },
      { name: "Sparkling", slug: "sparkling-wine", sortOrder: 4 },
      { name: "Indian Wine", slug: "indian-wine", sortOrder: 5 },
    ],
  },
  {
    name: "Brandy",
    slug: "brandy",
    description: "Spirit distilled from wine or fermented fruit",
    sortOrder: 7,
    subcategories: [
      { name: "Cognac", slug: "cognac", sortOrder: 1 },
      { name: "Indian Brandy", slug: "indian-brandy", sortOrder: 2 },
      { name: "Fruit Brandy", slug: "fruit-brandy", sortOrder: 3 },
    ],
  },
  {
    name: "Tequila",
    slug: "tequila",
    description: "Agave-based Mexican spirit",
    sortOrder: 8,
    subcategories: [
      { name: "Blanco", slug: "tequila-blanco", sortOrder: 1 },
      { name: "Reposado", slug: "tequila-reposado", sortOrder: 2 },
      { name: "Anejo", slug: "tequila-anejo", sortOrder: 3 },
    ],
  },
  {
    name: "Liqueur",
    slug: "liqueur",
    description: "Sweetened flavored spirit",
    sortOrder: 9,
    subcategories: [
      { name: "Cream Liqueur", slug: "cream-liqueur", sortOrder: 1 },
      { name: "Fruit Liqueur", slug: "fruit-liqueur", sortOrder: 2 },
      { name: "Herbal Liqueur", slug: "herbal-liqueur", sortOrder: 3 },
      { name: "Coffee Liqueur", slug: "coffee-liqueur", sortOrder: 4 },
    ],
  },
];

export const TAGS = [
  { name: "date night", slug: "date-night", tagType: "OCCASION" as const },
  { name: "house party", slug: "house-party", tagType: "OCCASION" as const },
  { name: "solo drinking", slug: "solo-drinking", tagType: "OCCASION" as const },
  { name: "celebration", slug: "celebration", tagType: "OCCASION" as const },
  { name: "first time", slug: "first-time", tagType: "TOPIC" as const },
  { name: "budget friendly", slug: "budget-friendly", tagType: "TOPIC" as const },
  { name: "premium", slug: "premium-pick", tagType: "TOPIC" as const },
  { name: "hangover cure", slug: "hangover-cure", tagType: "TOPIC" as const },
  { name: "cocktail recipe", slug: "cocktail-recipe", tagType: "TOPIC" as const },
  { name: "bar recommendation", slug: "bar-recommendation", tagType: "TOPIC" as const },
  { name: "drunk story", slug: "drunk-story", tagType: "TOPIC" as const },
  { name: "food pairing", slug: "food-pairing", tagType: "TOPIC" as const },
  { name: "chill vibes", slug: "chill-vibes", tagType: "MOOD" as const },
  { name: "party mode", slug: "party-mode", tagType: "MOOD" as const },
  { name: "romantic", slug: "romantic-mood", tagType: "MOOD" as const },
  { name: "adventurous", slug: "adventurous-mood", tagType: "MOOD" as const },
];
